version: "2"
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      extensions:
      - .js
      - .jsx
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
exclude_patterns:
  - "src/packages/*/src/*.test.js"
  - "src/packages/*/src/*.test.jsx"
